---
authorized_users:
- {name: acohea, key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF+JYZI4BvUkodAawax9HhtZsZtePTopV9u2tlIQnQyq acohea@chivalry}
- {name: acohea, key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN0IRRbaHTvKN1z1X3AH4PhRRjFtxE75tDtgv7l8A6R7 acohea@sigint}
- {name: jjs0sbw, key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfBrfMN9TN+ZPOPmav0+pwfThkkNrNRkT1Zzp+qlmqFzBV2o9CXTYapXbTAKvwHovf1/1lUfrEfxBVa5HkZm1WjlL5Mf0951PatrJVx14VcAH6QetP7X9wU7JY+dD+a3Ai+Uc1yoLVG4ypRureI0516yJPjk0v36F6xM99bIPlYBO7yEVDSwCaFe6HUuF+3znsGfNObNlfjCbnTVPvW+A5+Febxu77LLlfc5aJQzF60vs6u3je6InPqcJ+Cni6TfZF44M71MvekVFp2oiS3RBneXknzMhe4sJB0acZd2LpFeMCr1pe84+/Eq1TYsBiWIfghBg3ZPKFfQPegHjozg6F}
- {name: hasfaw, key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtLP/EykkYauUHfYfkt32AH/yGxlc2OY7cEYBKo04MUSPvVU0gcLQ8sHL/3aQUAgQMEOOPrlBdUGN5a0ZGOC0NqsQXEKkqvNCvkCVpiE2s+BSxadul7cbynBEU5KaGnHwCZZeCmk/ALanO0Egpx8YfbX8LFlNUucIecxPXWxSuFbB48+U8kHYR/Ul558bo0qmYXbJRO1vopYugIglDrljO9fqxJTQcuGHINfuryNVXohPssQHt589mePii8DLYLMAyUJdRo07zhXZ31LSkNq2Xuis/xHLsJzzVlURmg7eNJOycbRlEHxnufkCVYxa+9BJ2Q+UQZ4ibaNyd/g79uz/z}
domain: uwsg.tech
letsencrypt_account_key: /etc/ssl/private/letsencrypt_account.key
letsecnrypt_acme_directory: https://acme-staging.api.letsencrypt.org/directory
tls_private_key_path: /etc/ssl/private/privatekey.pem
tls_public_key_path: /etc/ssl/private/publickey.pem
tls_certificate_output_path: /etc/ssl/private/certificate.pem
tls_certificate_request_path: /etc/ssl/private/csr.pem
